<a href="https://colab.research.google.com/github/SaiAmartya/LearningPytorch/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### The purpose of this program is to further explore and learn about **tensors**

In [1]:
import torch

In [2]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
# Reshape if we don't know the number of items, using -1
my_torch2 = torch.arange(10)
my_torch2 = my_torch2.reshape(-1,5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
# Using View
my_torch3 = torch.arange(10)
my_torch3 = my_torch3.view(2,5)
my_torch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
# with reshape and view, they will update
my_torch5 = torch.arange(10)
my_torch6 = my_torch5.reshape(2,5)
print(my_torch6)
my_torch5[1] = 4141
print(my_torch5)
print(my_torch6) # Reshaped torch updated automatically

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])
tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])


In [22]:
# Slices
my_torch7 = torch.arange(10)

# Grab a specific item
print(my_torch7[7]) # Different than just the number 7

my_torch8 = my_torch7.reshape(-1,2)
print(my_torch8)
print(my_torch8[:,1]) # The second item in each row (second column)

# Return column with same structure
print(my_torch8[:,1:]) # All rows, second column

tensor(7)
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
tensor([1, 3, 5, 7, 9])
tensor([[1],
        [3],
        [5],
        [7],
        [9]])
