<a href="https://colab.research.google.com/github/SaiAmartya/LearningPytorch/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### The purpose of this program is to further explore and learn about Pytorch **tensors**

In [72]:
import torch
import numpy as np

In [73]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [75]:
# Reshape if we don't know the number of items, using -1
my_torch2 = torch.arange(10)
my_torch2 = my_torch2.reshape(-1,5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [76]:
# Using View
my_torch3 = torch.arange(10)
my_torch3 = my_torch3.view(2,5)
my_torch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [77]:
# with reshape and view, they will update
my_torch5 = torch.arange(10)
my_torch6 = my_torch5.reshape(2,5)
print(my_torch6)
my_torch5[1] = 4141
print(my_torch5)
print(my_torch6) # Reshaped torch updated automatically

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])
tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])


In [78]:
# Slices
my_torch7 = torch.arange(10)

# Grab a specific item
print(my_torch7[7]) # Different than just the number 7

my_torch8 = my_torch7.reshape(-1,2)
print(my_torch8)
print(my_torch8[:,1]) # The second item in each row (second column)

# Return column with same structure
print(my_torch8[:,1:]) # All rows, second column

tensor(7)
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
tensor([1, 3, 5, 7, 9])
tensor([[1],
        [3],
        [5],
        [7],
        [9]])


**TENSOR MATH OPERATIONS**
- Add, subtract, Multiply, Divide, Remainders Exponents
- Shorthand and Longhand
- Reassignment

In [79]:
tensor_a = torch.arange(1,5)
tensor_b = torch.arange(5,9)

In [80]:
# Addition, Add both of the same indexes
print(tensor_a + tensor_b)
print(torch.add(tensor_a,tensor_b)) # add method

tensor([ 6,  8, 10, 12])
tensor([ 6,  8, 10, 12])


In [81]:
# Subtraction
print(tensor_b - tensor_a)
print(torch.sub(tensor_b, tensor_a)) # sub method

tensor([4, 4, 4, 4])
tensor([4, 4, 4, 4])


In [82]:
# Multiplication
print(tensor_a * tensor_b)
torch.mul(tensor_a, tensor_b) # mul longhand

tensor([ 5, 12, 21, 32])


tensor([ 5, 12, 21, 32])

In [83]:
# Division
print(tensor_b / tensor_a)
print(torch.div(tensor_b, tensor_a)) # div longhand

tensor([5.0000, 3.0000, 2.3333, 2.0000])
tensor([5.0000, 3.0000, 2.3333, 2.0000])


In [84]:
# Remainder Modulus
print(tensor_b % tensor_a)
print(torch.remainder(tensor_b, tensor_a)) # remainder longhand

tensor([0, 0, 1, 0])
tensor([0, 0, 1, 0])


In [85]:
# Exponents
print(tensor_b ** tensor_a) # b^a
print(torch.pow(tensor_b, tensor_a)) # pow longhand

tensor([   5,   36,  343, 4096])
tensor([   5,   36,  343, 4096])


In [86]:
# Another way to write longhand
print(tensor_a.add(tensor_b))
print(tensor_a.mul(tensor_b))
print(tensor_a.sub(tensor_b))
print(tensor_a.div(tensor_b))

tensor([ 6,  8, 10, 12])
tensor([ 5, 12, 21, 32])
tensor([-4, -4, -4, -4])
tensor([0.2000, 0.3333, 0.4286, 0.5000])


In [87]:
# Reassignment
tensor_a += tensor_b
print(tensor_a)
tensor_a.add_(tensor_b) # Reassign longhand
print(tensor_a)

tensor([ 6,  8, 10, 12])
tensor([11, 14, 17, 20])
